import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from '../providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const notoDisplay = Inter({
  subsets: ['latin'],
  variable: '--font-noto-display',
  display: 'swap',
});

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className={`${notoDisplay.variable} light`}>
      <body className="bg-primary-dark">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
