import './globals.css';
import React, { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import MUIProvider from '@/components/providers/MUIProvider';
import LocalizationProvider from '@/components/providers/LocalizationProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-noto-display',
  display: 'swap',
});

type Props = {
  children: ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className={`${inter.variable} light`}>
      <body className="bg-primary-dark">
        <LocalizationProvider>
          <MUIProvider>{children}</MUIProvider>
        </LocalizationProvider>
      </body>
    </html>
  );
}
